/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InterfaceWithC */

#ifndef _Included_InterfaceWithC
#define _Included_InterfaceWithC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InterfaceWithC
 * Method:    victory
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_InterfaceWithC_victory
  (JNIEnv * env, jclass cl, jintArray arr);

#ifdef __cplusplus
}
#endif
#endif
